### ISSUE TITLE
No 'wait'

### ISSUE THREAD

**Issue by mcowger** [dnaeon/py-vevents#1]
Not a bug, but I noticed this little snippet:

```
    while True:
        # New events will be inserted at the first element in the collector.latestPage list
        event = collector.latestPage[0]
```

Any concerns about not having a wait in there of some sort between repeated requests for the entire page of most recent events?

I haven't profiled it, but I have to imagine its somewhat impactful.

**Comment by dnaeon** [comment]
Added a sleep interval in https://github.com/dnaeon/py-vevents/commit/cdc492c2ac743040bb2a3a171cf25243eb4d9a0a, which should take care of this behaviour.

Thanks for reporting this!

Regards,
Marin
